channels:
- conda-forge
- defaults
dependencies:
- affine
- dask
- gcsfs
- geopandas
- ipython
- jupyter
- matplotlib
- netCDF4
- numpy
- pandas
- pip
- pyextremes
- pygeoprocessing
- pytest
- rasterio
- rechunker
- seaborn
- xarray
- zarr
- pip:
  - taskgraph
